# Generated by Django 3.2.6 on 2022-10-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglicence',
            name='task_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
